### ISSUE TITLE
Show preview image/gif in Readme.md

### ISSUE THREAD

**Issue by rahuldeepattri** [endormi/vscode-2077-theme#19]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i can't preview what theme would look like.

**Describe the solution you'd like**
Any image/gif showing how vscode will look like after applying the theme.

**Comment by endormi** [comment]
Thanks for the request!

I used to have an preview image in the `README.md` file, but removed it since the quality of the images weren't the greatest and thought it might have negative results with new downloads. It looks great on GitHub, but on marketplace, it's not the greatest. l I might be adding it back or not, I'll come back with the answer ASAP.

**Comment by bhajneet** [comment]
Perhaps you could add the image to somewhere else in the repo and add a link pointing to it in the README

**Comment by endormi** [comment]
Yeah, I might do that 👍

**Comment by endormi** [comment]
I added it directly to `README.md`.
